name: ism_video_reel_player_example
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.6.0
description: Demonstrates how to use the ism_video_reel_player plugin.

dependencies:
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  cloudinary: ^1.2.0
  connectivity_plus: ^7.0.0
  country_phone_validator: ^1.0.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  ffmpeg_kit_flutter_new: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fluttertoast: ^8.2.14
  get_it: ^8.2.0
  get_thumbnail_video: ^0.7.3
  go_router: ^16.2.1
  googleapis_auth: ^2.0.0
  image_picker: ^1.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  ism_video_reel_player:
    path: ../
  lottie: ^3.3.2
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pro_image_editor: ^11.5.7
  pro_video_editor: ^0.2.3
  timeago: ^3.7.1
  video_compress: ^3.1.4
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/json/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayFair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayFair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Black.ttf
          weight: 900
    - family: Agenda
      fonts:
        - asset: assets/fonts/Agenda/Agenda-Light.ttf
          weight: 300
        - asset: assets/fonts/Agenda/Agenda-Black.ttf
          weight: 900
        - asset: assets/fonts/Agenda/Agenda-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
