name: ism_video_reel_player_example
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.6.0
description: Demonstrates how to use the ism_video_reel_player plugin.
dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  cloudinary: ^1.2.0
  connectivity_plus: ^6.1.3
  country_phone_validator: ^1.0.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.3
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.11
  get_it: ^8.0.3
  go_router: ^16.2.4
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  ism_video_reel_player:
    path: ../
  path: ^1.9.1
  path_provider: ^2.1.5
#  video_thumbnail: ^0.5.3
  get_thumbnail_video: ^0.7.3
  web: ^1.1.0
dev_dependencies:
  build_runner: '^2.4.11'
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
dependency_overrides:
  path: '^1.9.1'
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/json/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayFair/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayFair/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayFair/PlayfairDisplay-Black.ttf
          weight: 900
    - family: Agenda
      fonts:
        - asset: assets/fonts/Agenda/Agenda-Light.ttf
          weight: 300
        - asset: assets/fonts/Agenda/Agenda-Black.ttf
          weight: 900
        - asset: assets/fonts/Agenda/Agenda-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
