/// English fallback strings when EasyLocalization is unavailable.
const Map<String, String> kIsrTrFallback = {
  'timeoutError':
      'Oops! The request took too long to process. Please check your internet connection and try again. If the issue persists, you can contact our support team for assistance.',
  'somethingWentWrong': 'Something went wrong',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'Ok',
  'next': 'Next',
  'cancel': 'Cancel',
  'close': 'Close',
  'continues': 'Continue',
  'alert': 'Alert',
  'follow': 'Follow',
  'request': 'Request',
  'requested': 'Requested',
  'withdrawFollowRequestTitle': 'Withdraw request',
  'withdrawFollowRequestMessage': 'Do you want to withdraw your request?',
  'keepFollowRequest': 'Keep request',
  'withdrawFollowRequest': 'Withdraw',
  'followRequests': 'Follow requests',
  'incoming': 'Incoming',
  'outgoing': 'Outgoing',
  'accept': 'Accept',
  'decline': 'Decline',
  'cancelRequest': 'Cancel',
  'noIncomingRequests': 'No incoming requests',
  'noOutgoingRequests': 'No outgoing requests',
  'blockedUsers': 'Blocked users',
  'searchBlockedUsers': 'Search blocked users',
  'unblock': 'Unblock',
  'unblockUser': 'Unblock user',
  'unblockUserConfirmation': 'Are you sure you want to unblock this user?',
  'noBlockedUsers': 'No blocked users',
  'noBlockedUsersMessage': 'Users you block will appear here.',
  'userUnblockedSuccessfully': 'User unblocked successfully',
  'userBlockedSuccessfully': 'User blocked successfully',
  'required': 'Required',
  'passwordValidationString':
      'You need to enter at least 8 characters , with X capital , y special characters and z small alphabets and q digits',
  'invalidEmail': 'Invalid Email',
  'following': 'Following',
  'trending': 'Trending',
  'create': 'Create',
  'createAPost': 'Create a Post',
  'addAProduct': 'Add a product',
  'addASound': 'Add a Sound',
  'newPost': 'New Post',
  'newReel': 'New Reel',
  'writeCaption': 'Write a caption...',
  'category': 'Category',
  'selectCategory': 'Select Category',
  'allowComments': 'Allow Comments',
  'allowSave': 'Allow Save',
  'allowDownloads': 'Allow Downloads',
  'post': 'Post',
  'sdkNotInitialized': 'sdk not initialized',
  'noInternet': 'No Internet',
  'shop': 'Shop',
  'product': 'Product',
  'products': 'Products',
  'more': 'More',
  'save': 'Save',
  'saved': 'Saved',
  'share': 'Share',
  'mute': 'Mute',
  'unmute': 'Unmute',
  'notFollowingAnyone': 'Not Following Anyone!',
  'findPeopleToFollow': 'Find People to follow',
  'noPostAvailable': 'No Post Available',
  'startFollowing': 'Start following to see contents.',
  'creatorEarnsCommission': 'Creator Earns Commission',
  'viewMore': 'View More',
  'viewLess': 'View Less',
  'paidPostLockedTitle': 'Paid content',
  'paidPostLockedSubtitle': 'Unlock this post to view the full media.',
  'unlockFor': 'Unlock for',
  'uploadPhotoOrVideo': 'Upload a photo or a video',
  'description': 'Description',
  'writeDescription': 'Write a description',
  'cover': 'Cover',
  'editCover': 'Edit Cover',
  'changeCover': 'Change Cover',
  'addCover': 'Add Cover',
  'whenToPost': 'When to post',
  'now': 'Now',
  'schedule': 'Schedule',
  'schedulePost': 'Schedule Post',
  'linkProductsToPost': 'Link Products to Post',
  'linkProducts': 'Link Products',
  'addLink': 'Add Link',
  'addLinkDescription':
      'Add an https link and a title. Viewers can tap the button on your reel.',
  'linkUrl': 'Link URL',
  'linkTitle': 'Link title',
  'linkTitleHint': 'e.g. Shop now, Learn more',
  'enterLinkUrl': 'Enter a link URL',
  'enterValidHttpsLinkUrl': 'URL must use https',
  'enterButtonLabel': 'Enter a link title',
  'removeLink': 'Remove link',
  'noProductsLinkedYet': 'No products linked yet!',
  'connectProductsToPost':
      'Connect products to posts for better visibility and engagement',
  'addProducts': 'Add Products',
  'choosePhotoOrVideo': 'Choose photo or video',
  'noNakedPicture': 'No naked picture. No soliciting. No escort services',
  'takePhoto': 'Take photo',
  'selectImageFromGallery': 'Select image from gallery',
  'takeVideo': 'Take video',
  'selectVideoFromGallery': 'Select video from gallery',
  'change': 'Change',
  'size': 'Size',
  'duration': 'Duration',
  'socialPostCreatedSuccessfully': 'Social post created successfully',
  'postUpdatedSuccessfully': 'Post updated successfully',
  'postScheduledSuccessfully': 'Post scheduled successfully',
  'successfullyPosted': 'Successfully Posted',
  'successfullyEdited': 'Successfully Edited',
  'successfullyScheduled': 'Successfully Scheduled',
  'createPost': 'Create Post',
  'moreOptions': 'More Options',
  'reportPost': 'Report Post',
  'postReportedSuccessfully': 'Post reported successfully',
  'report': 'Report',
  'download': 'Download',
  'downloading': 'Downloading...',
  'downloadSavedToGallery': 'Saved to your gallery',
  'downloadFailed': 'Could not download this reel',
  'downloadNotAllowed': 'Downloads are not allowed for this post',
  'downloadPermissionDenied': 'Allow photo library access to save reels',
  'dubWithAudio': 'Dub with audio',
  'dubLockedPostMessage': 'Unlock this post before recording a dub.',
  'dubNoVideoMessage': 'This post has no video to dub.',
  'dubExtractAudioFailedMessage': 'Could not extract audio from this reel.',
  'useAudio': 'Use audio',
  'soundPreviewUnavailable': 'Preview is not available for this sound.',
  'soundPreviewPlayFailed': 'Could not play preview',
  'soundDetailReelSingular': 'Reel',
  'soundDetailReelsPlural': 'Reels',
  'soundDetailUntitled': 'Untitled',
  'soundDetailUnknownArtist': 'Unknown artist',
  'soundDetailShareSoon': 'Sharing will be available soon',
  'soundDetailNoPosts': 'No posts use this sound yet',
  'tryAgain': 'Try again',
  'reports': 'Reports',
  'confirm': 'Confirm',
  'failedToLoadReportReasons': 'Failed to load report reasons',
  'noReportReasonsAvailable': 'No report reasons are available at the moment.',
  'selectDate': 'Select Date',
  'uploadingVideo': 'Uploading Video',
  'uploadingImage': 'Uploading Image',
  'uploadingCoverImage': 'Uploading Cover Image',
  'editPost': 'Edit Post',
  'updatePost': 'Update Post',
  'remove': 'Remove',
  'optimizingMedia': 'Optimizing media',
  'time': 'Time',
  'pleaseSelectAFutureTime': 'Please select a future time.',
  'yourPostHasBeenSuccessfullyPosted':
      'Your post has been successfully posted.',
  'date': 'Date',
  'postingPost': 'Posting Post',
  'edit': 'Edit',
  'delete': 'Delete',
  'deletePost': 'Delete Post',
  'deleteThisPost': 'Delete this post?',
  'deleteThisPostMessage':
      "This can't be undone. The post and all its data will be permanently removed.",
  'confirmDelete': 'Confirm Delete',
  'deletePostConfirmation': 'Are you sure you want to delete this post?',
  'postDetails': 'Post Details',
  'rejected': 'Rejected',
  'scheduled': 'Scheduled',
  'tapForDetails': 'Tap for details',
  'editAndResubmit': 'Edit & Resubmit',
  'withdrawPost': 'Withdraw Post',
  'editSubmission': 'Edit Submission',
  'publishNow': 'Publish Now',
  'postDetailsAwaitingReview': 'Awaiting Review',
  'postDetailsAwaitingReviewMessage':
      "Your post is in the queue. Reviews usually complete within 24–48 hours. You'll be notified as soon as there's an update.",
  'postDetailsScheduledPostTitle': 'Scheduled Post',
  'postDetailsScheduledPostMessage':
      'This post is approved and will publish automatically. You can even publish it now.',
  'postDetailsResubmittedTitle': 'Post Resubmitted!',
  'postDetailsDefaultRejectionReason':
      'This item did not meet our content standards.',
  'postDetailsSubmittedLabel': 'Submitted',
  'postDetailsReviewedLabel': 'Reviewed',
  'postDetailsRejectedOnLabel': 'Rejected',
  'postDetailsScheduledForLabel': 'Scheduled for',
  'deleteStory': 'Delete Story?',
  'deleteStoryConfirmation':
      'Are you sure you want to delete this story? This action cannot be undone.',
  'postNowConfirmation': 'Are you sure you want to Post Now?',
  'reportPostConfirmation': 'Are you sure you want to report this post?',
  'editPostConfirmation': 'Are you sure you want to edit the post?',
  'postDeletedSuccessfully': 'Post deleted successfully',
  'allComments': 'Comments',
  'reply': 'Reply',
  'viewReplies': 'View Replies',
  'hideReplies': 'Hide Replies',
  'like': 'like',
  'likes': 'likes',
  'addAComment': 'Join the conversation...',
  'addAReply': 'Add a reply...',
  'replyingTo': 'Replying to',
  'noCommentsYet': 'No Comments Yet',
  'beTheFirstOneToPostAComment': 'Be the first one to post a comment',
  'commentReportedSuccessfully': 'Comment reported successfully',
  'failedToUpdateWishlistStatus': 'Failed to update wishlist status',
  'justNow': 'Just now',
  'noPostsFound': 'No posts found',
  'inThisSocialPost': 'In this social post',
  'removeMeFromPost': 'Remove me from post',
  'removeTag': 'Remove tag',
  'removeMeFromPostTitle': 'Remove yourself from this post?',
  'removeMeFromPostMessage': 'Your  will no longer appear on this post.',
  'mentionRemovedSuccessfully': 'You have been removed from this post',
  'retry': 'Retry',
  'noPostsDescription':
      'No posts have been shared for this location yet. Be the first to share something!',
  'postInsight': 'Post Insight',
  'views': 'Views',
  'interactions': 'Interactions',
  'followers': 'Followers',
  'nonFollowers': 'Non-Followers',
  'overview': 'Overview',
  'profileActivity': 'Profile activity',
  'topLocations': 'Top Locations',
  'statistics': 'Statistics',
  'profileVisits': 'Profile visits',
  'comments': 'Comments',
  'saves': 'Saves',
  'shares': 'Shares',
  'accountEngaged': 'Account Engaged',
  'follows': 'Follows',
  'pleaseSelectMinimumResolution':
      'Please select media with minimum resolution of 240 x 240 pixels',
  'allFilesUploadedSuccessfully': 'All files uploaded successfully',
  'uploadingMediaFiles': 'Uploading Media Files',
  'uploadingCoverFiles': 'Uploading Cover Files',
  'uploadingPreviewFiles': 'Uploading Preview Files',
  'uploadComplete': 'Upload Complete',
  'successfullyUploaded': 'Successfully Uploaded',
  'mediaUploadFailedTryAgain':
      'Upload failed. Please try again to upload pending files.',
  'uploadFailed': 'Upload Failed',
  'yourMediaFilesHaveBeenUploadedSuccessfully':
      'Your media files have been uploaded successfully',
  'tagPeople': 'Tag People',
  'tagLocation': 'Tag location',
  'people': 'People',
  'addLocation': 'Add Location',
  'addCaption': 'Add a caption',
  'afterTalentsBack': 'After Talents Back',
  'talentsBack': 'Talents Back',
  'link': 'Link',
  'unLink': 'Unlink',
  'linked': 'Linked',
  'saveChanges': 'Save changes',
  'outOfStock': 'Out of stock',
  'notifyMe': 'Notify me',
  'timeSeries': 'Time Series',
  'earn': 'Earn',
  'talents': 'talents',
  'choosePhoto': 'Choose photo',
  'chooseVideo': 'Choose video',
  'taggedPeople': 'Tagged People',
  'listOfPeopleLinkedToThePost': 'List of people linked to the post',
  'search': 'Search',
  'noPeopleFound': 'No people found',
  'selectedPeople': 'Selected People',
  'noPeopleSelected': 'No people selected',
  'searchForPeople': 'Search for people',
  'noUserFound': 'No User Found',
  'startTypingToFindPeopleToTag': 'Start typing to find people to tag',
  'noLocationFound': 'No Location Found',
  'trySearchingWithADifferentName': 'Try searching with a different name',
  'posting': 'Posting...',
  'inReview': 'In Review',
  'searchLocation': 'Search location',
  'searchForALocation': 'Search for a location',
  'startTypingToFindPlaces': 'Start typing to find places',
  'selectALocation': 'Select a location',
  'seePlacesNearYou': 'See places near you',
  'near': 'Near',
  'manageCollections': 'Manage Collections',
  'createANewCollection': 'Create a new collection',
  'public': 'Public',
  'private': 'Private',
  'createNewCollection': 'Create New Collection',
  'collections': 'Collections',
  'allCollection': 'All Collections',
  'untitledCollection': 'Untitled Collection',
  'editCollection': 'Edit Collection',
  'collectionName': 'Collection Name',
  'shareSettings': 'Share Settings',
  'onlyYouCanView': 'Only you can view',
  'anyoneCanView': 'Anyone can view',
  'addToAnotherCollection': 'Add To Another Collection',
  'removeFromCollection': 'Remove From Collection',
  'createdSuccessfully': 'created successfully',
  'updatedSuccessfully': 'updated successfully',
  'savingPost': 'Saving Post',
  'newCollection': 'New Collection',
  'yourSavedProducts': 'Your Saved Products',
  'done': 'Done',
  'savedPosts': 'Saved Posts',
  'makeThisCollectionPrivate': 'Make this collection private',
  'collectionsMessage': 'When you create collections, they will appear here.',
  'createCollectionButton': 'Create a Collection',
  'chooseFromGallery': 'Choose From Gallery',
  'createCollection': 'Create collection',
  'characters': 'Characters',
  'scheduledPosts': 'Scheduled Posts',
  'myScheduledPosts': 'My Scheduled Posts',
  'noScheduledPosts': 'No Scheduled Posts',
  'addNewScheduledPosts': 'Add new Scheduled Posts',
  'postNow': 'Post Now',
  'modifySchedule': 'Modify Schedule',
  'newStory': 'New Story',
  'createNewHighlight': 'Create new highlight',
  'editHighlight': 'Edit highlight',
  'editHighlightCover': 'Edit cover',
  'highlightNameHint': 'Highlight name',
  'highlightStoriesSection': 'STORIES',
  'addStoriesToHighlight': 'Add stories',
  'addToExistingHighlight': 'Add to existing highlight',
  'addToHighlights': 'Add to highlights',
  'noHighlightsCreateFirst': 'No highlights yet. Tap + to create one.',
  'highlightEmptyTitle': 'No stories in this highlight',
  'highlightEmptySubtitle':
      'Add stories from your archive or post a new story.',
  'reportStory': 'Report',
  'pickPhoto': 'Pick photo',
  'pickVideo': 'Pick video',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'writeToAddToStory': ' Add caption to your story',
  'shareStory': 'Share story',
  'yourStory': 'Your Story',
  'uploadPhotoOrVideoToInspire':
      'Upload a photo or a video to inspire and connect with our {appName} community.',
  'reportAlertTitle': 'Report {type}',
  'postDetailsResubmittedMessage':
      "Your {count} replaced item{plural} are now under admin review. The rest of your post is live and unchanged. You'll get a notification once the review is complete.",
  'postDetailsRejectedItemsCount': '{rejected} of {total} items rejected',
  'postDetailsRejectedItemsFallbackSingular': '1 item rejected',
  'postDetailsRejectedItemsFallbackPlural': '{count} items rejected',
  'postReviewImageLabel': 'Image #{number}',
  'postReviewVideoLabel': 'Video #{number}',
  'reportConfirmation': 'Are you sure you want to report this {type}?',
  'reportedSuccessfully': '{type} reported successfully',
  'addAStory': 'Add a story',
  'paidPost': 'Paid post',
  'music': 'Music',
  'sound': 'Sound',
  'searchSoundsArtistsAlbums': 'Search sounds, artists, albums',
  'browseCategories': 'BROWSE CATEGORIES',
  'all': 'All',
  'recent': 'Recent',
  'recommended': 'Recommended',
  'results': 'Results',
  'trendingSongs': 'Trending Songs',
  'savedSounds': 'Saved',
  'viewAll': 'View all',
  'noSoundsFound': 'No sounds found',
  'tryDifferentSoundFilter': 'Try a different tab, category, or search keyword.',
  'couldNotLoadSounds': 'Could not load sounds',
  'couldNotUpdateSavedSound': 'Could not update saved sound',
  'lyrics': 'Lyrics',
  'useThisSound': 'Use this sound',
};
